### ISSUE TITLE
ETS created from schematron fails [err:FORG0006] Effective boolean value not defined for 

### ISSUE THREAD

**Issue by thijsbrentjens** [interactive-instruments/etf-ets-repository#7]
From a Schematron file I created an ETS with the XSLs from the utils. It does not validate a metadata record which does validate using the schematron rules itself.

Running the test results in several errors, all with a similar message.
Description:
```
System error in the Executable Test Suite. Please contact a system administrator. Error information:
[err:FORG0006] Effective boolean value not defined for (false(), false(), ...). 
 (163/8)
```
I don't understand what is happening exactly. Could you help @jonherrmann  ?

Example failing assertion:
http://beta.validatie.geostandaarden.nl:8080/etf-webapp-2.0.0/v2/TestRuns/EID9f7b43d2-f8f9-4455-a903-8b2ca1ce7dbd.html#EID3b07d2f9-cdde-4a14-9c1b-46ed28aa2d7a

If needed, I'll provide a metadata document to reproduce this.

**Comment by cportele** [comment]
@thijsbrentjens - I will have a look at it.

**Comment by cportele** [comment]
@thijsbrentjens - Could you email me a metadata record that we can use for testing? Thanks.

**Comment by jonherrmann** [comment]
Issue fixed in PR #8

**Comment by jonherrmann** [comment]
Reopening due to an issue with this schematron file:

[schematron.sch.txt](https://github.com/interactive-instruments/etf-ets-repository/files/1775570/schematron.sch.txt)

> System error in the Executable Test Suite. Please contact a system administrator. Error information:
[err:XPST0008] Undefined variable $all_conformity_Spec_Titles_join. 
 (172/14)

**Comment by jonherrmann** [comment]
Please note that the Executable Test Suites must be re-generated using the updated [schematron_2_etf_ets.xsl](https://github.com/interactive-instruments/etf-ets-repository/blob/master/utils/schematron_2_etf_ets.xsl) in order to fix this issue. J

**Comment by thijsbrentjens** [comment]
Thanks @jonherrmann , works smoothly
